default_platform(:android)

platform :android do
  desc "Build and deploy to the Play Store production track"
  lane :deploy do
    sh("flutter", "clean")
    sh("flutter", "pub", "get")
    sh("flutter", "build", "appbundle", "--release")

    upload_to_play_store(
      track: "production",
      aab: File.expand_path("../../build/app/outputs/bundle/release/app-release.aab", __dir__),
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )

    upload_to_play_store(
      track: "production",
      track_promote_to: "beta",
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Build and deploy to the Play Store beta track"
  lane :beta do
    sh("flutter", "clean")
    sh("flutter", "pub", "get")
    sh("flutter", "build", "appbundle", "--release")

    upload_to_play_store(
      track: "beta",
      aab: File.expand_path("../../build/app/outputs/bundle/release/app-release.aab", __dir__),
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
